SET SERVEROUTPUT ON;
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TESTE';
	EXECUTE IMMEDIATE 'CREATE TABLE TESTE(col1 NUMBER, col2 VARCHAR2(50))';
	EXECUTE IMMEDIATE 'INSERT INTO TESTE(col1, col2) VALUES(1,''JORGE'')';
    EXECUTE IMMEDIATE 'INSERT INTO TESTE(col1, col2) VALUES(2,''ANA'')';
    EXECUTE IMMEDIATE 'INSERT INTO TESTE(col1, col2) VALUES(3,''CAMILLE'')';
    EXECUTE IMMEDIATE 'INSERT INTO TESTE(col1, col2) VALUES(4,''KAREN'')';
    EXECUTE IMMEDIATE 'INSERT INTO TESTE(col1, col2) VALUES(5,''HUMBERTO'')';
    EXECUTE IMMEDIATE 'INSERT INTO TESTE(col1, col2) VALUES(6,''PINGO'')';
    EXECUTE IMMEDIATE 'INSERT INTO TESTE(col1, col2) VALUES(7,''NOUR'')';
END;
/

select * from teste;

SET SERVEROUTPUT ON;
DECLARE
    v_String VARCHAR2(200);
BEGIN
    FOR r_c1 IN (SELECT * FROM USER_TABLES) LOOP
        v_String := 'delete from '||r_c1.table_name||';';
        DBMS_OUTPUT.PUT_LINE(v_String);
        EXECUTE IMMEDIATE v_String;
    END LOOP;
    COMMIT;
END;
/