-- MySQL Script generated by MySQL Workbench
-- Sun Jan 24 18:49:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_comercio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_comercio` (
  `id_com` INT NOT NULL,
  `nome_com` VARCHAR(100) NULL,
  `tp_com` VARCHAR(45) NULL COMMENT 'tipo do comércio. Ex: mercado, vestuário etc',
  `logradouro` VARCHAR(60) NULL,
  `cidade` VARCHAR(60) NULL,
  `uf` VARCHAR(2) NULL,
  PRIMARY KEY (`id_com`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_contato` (
  `id_contato` INT NOT NULL,
  `numero` VARCHAR(11) NOT NULL,
  `tb_comercio_id_com` INT NOT NULL,
  PRIMARY KEY (`id_contato`, `tb_comercio_id_com`),
  INDEX `fk_tb_contato_tb_comercio1_idx` (`tb_comercio_id_com` ASC) VISIBLE,
  CONSTRAINT `fk_tb_contato_tb_comercio1`
    FOREIGN KEY (`tb_comercio_id_com`)
    REFERENCES `mydb`.`tb_comercio` (`id_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `id_prod` INT NULL,
  `descricao_prod` VARCHAR(100) NULL,
  `peso_prod` DOUBLE NULL COMMENT 'peso em gramas',
  `dt_validade` DATE NULL,
  `preco` DOUBLE NOT NULL,
  `dt_fabricacao` DATE NULL,
  PRIMARY KEY (`id_prod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_fabricante` (
  `id_fabricante` INT NULL,
  `nm_fabricante` VARCHAR(100) NULL,
  PRIMARY KEY (`id_fabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_fabricante_x_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_fabricante_x_produto` (
  `fabricante_id_fabricante` INT NOT NULL,
  `produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`fabricante_id_fabricante`, `produto_id_produto`),
  INDEX `fk_fabricante_has_produto_produto1_idx` (`produto_id_produto` ASC) VISIBLE,
  INDEX `fk_fabricante_has_produto_fabricante1_idx` (`fabricante_id_fabricante` ASC) VISIBLE,
  CONSTRAINT `fk_fabricante_has_produto_fabricante1`
    FOREIGN KEY (`fabricante_id_fabricante`)
    REFERENCES `mydb`.`tb_fabricante` (`id_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fabricante_has_produto_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `mydb`.`tb_produto` (`id_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_comercio_x_tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_comercio_x_tb_produto` (
  `tb_comercio_id_com` INT NOT NULL,
  `tb_produto_id_prod` INT NOT NULL,
  PRIMARY KEY (`tb_comercio_id_com`, `tb_produto_id_prod`),
  INDEX `fk_tb_comercio_has_tb_produto_tb_produto1_idx` (`tb_produto_id_prod` ASC) VISIBLE,
  INDEX `fk_tb_comercio_has_tb_produto_tb_comercio1_idx` (`tb_comercio_id_com` ASC) VISIBLE,
  CONSTRAINT `fk_tb_comercio_has_tb_produto_tb_comercio1`
    FOREIGN KEY (`tb_comercio_id_com`)
    REFERENCES `mydb`.`tb_comercio` (`id_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_comercio_has_tb_produto_tb_produto1`
    FOREIGN KEY (`tb_produto_id_prod`)
    REFERENCES `mydb`.`tb_produto` (`id_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
